[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "@chainlink/contracts-ccip=node_modules/@chainlink/contracts-ccip",
    "@everest/contracts=lib/hardhat-everest-chainlink-consumer/contracts",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
